project:
  type: website
  output-dir: docs
resources:
  - particles.json  
lang: ar
dir: rtl
website:
  title: ""
  search: false
  favicon: logo.png
  navbar:
    title: false
    logo: logo.png
    logo-alt: "شعار رؤية للاستشارات"
    right:
      - href: about.qmd
        text: من نحن
      - href: our-work.qmd
        text: أعمالنا
      - href: index.qmd
        text: الرئيسية
  page-footer: 
    background: light
    center: "Copyright 2025, Roya Consultancy"      
  
format:
  html:
    
    theme: 
    - cosmos
    - styles.scss
    mainfont: Muna
    page-layout: full


editor: visual

