project:
  type: website
  output-dir: docs
resources:
  - particles.json  
lang: ar
dir: rtl
website:
  title: ""
  search: false
  favicon: logo.png
  navbar:
    sort: false
    title: false
    logo: logo.png
    logo-alt: "شعار رؤية للاستشارات"
    right:
      - href: "#services"
        text: خدماتنا
      - href: "#about"
        text: من نحن
      - href: "#"
        text: المدونة
      - href: index.qmd
        text: الرئيسية
  # page-footer: 
  #   background: light
  #   center: "Copyright 2025, Roya Consultancy"  
  
format:
  html:
    theme: 
    - cosmos
    - styles.scss
    mainfont: Amiri
    page-layout: full

editor: visual

